<div class="container login-container register-form">
    <h1>Register</h1>
    <form method='post'>
        <div class="form-group">
            <label>
                Name *
            </label>

            <?php echo $registerForm->render('name'); ?>
        </div>
        <div class="form-group">

            <label>
                Email *
            </label>

            <?php echo $registerForm->render('email'); ?>
        </div>
        <div class="form-group">

            <label>
                Password *
            </label>

            <?php echo $registerForm->render('password'); ?>
        </div>
        <div class="form-group">

            <label>
                Password confirm *
            </label>

            <?php echo $registerForm->render('confirm_password'); ?>
        </div>

        <div class="form-group">
            <input type='submit' class="btnSubmit" value='Register'/>
        </div>
    </form>
</div>